# Generated by Django 3.2.8 on 2022-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_attendance_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(blank=True, choices=[('absent', 'Absent'), ('present', 'Present')], max_length=8),
        ),
    ]
